# Generated by Django 4.1.3 on 2022-12-06 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad_blocking", models.BooleanField()),
                ("yt_sub", models.BooleanField()),
                (
                    "pastuse_brands",
                    models.ManyToManyField(
                        related_name="produse_brands", to="form.brand"
                    ),
                ),
                (
                    "produse_brands",
                    models.ManyToManyField(related_name="seen_brands", to="form.brand"),
                ),
                ("seen_brands", models.ManyToManyField(to="form.brand")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
