# Generated by Django 4.1.3 on 2022-12-07 12:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppriseMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Emotions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emotion", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="form.brand"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad_blocking", models.BooleanField()),
                ("yt_sub", models.BooleanField()),
                ("youtube_percentage", models.IntegerField()),
                (
                    "gpa",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(4.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ]
                    ),
                ),
                (
                    "brand_Automobiles_0",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("product_Automobiles_0", models.CharField(max_length=255)),
                (
                    "brand_Automobiles_1",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("product_Automobiles_1", models.CharField(max_length=255)),
                (
                    "brand_Automobiles_2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("product_Automobiles_2", models.CharField(max_length=255)),
                (
                    "brand_Clothing and Apparel_0",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("product_Clothing and Apparel_0", models.CharField(max_length=255)),
                (
                    "brand_Clothing and Apparel_1",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("product_Clothing and Apparel_1", models.CharField(max_length=255)),
                (
                    "brand_Clothing and Apparel_2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("product_Clothing and Apparel_2", models.CharField(max_length=255)),
                (
                    "brand_Cosmetics_0",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("product_Cosmetics_0", models.CharField(max_length=255)),
                (
                    "brand_Cosmetics_1",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("product_Cosmetics_1", models.CharField(max_length=255)),
                (
                    "brand_Cosmetics_2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("product_Cosmetics_2", models.CharField(max_length=255)),
                (
                    "brand_Electronics_0",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("product_Electronics_0", models.CharField(max_length=255)),
                (
                    "brand_Electronics_1",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("product_Electronics_1", models.CharField(max_length=255)),
                (
                    "brand_Electronics_2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("product_Electronics_2", models.CharField(max_length=255)),
                (
                    "brand_Telecom_0",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("product_Telecom_0", models.CharField(max_length=255)),
                (
                    "brand_Telecom_1",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("product_Telecom_1", models.CharField(max_length=255)),
                (
                    "brand_Telecom_2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("product_Telecom_2", models.CharField(max_length=255)),
                (
                    "brand_Healthcare_0",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("product_Healthcare_0", models.CharField(max_length=255)),
                (
                    "brand_Healthcare_1",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("product_Healthcare_1", models.CharField(max_length=255)),
                (
                    "brand_Healthcare_2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("product_Healthcare_2", models.CharField(max_length=255)),
                (
                    "brand_Food_0",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("product_Food_0", models.CharField(max_length=255)),
                (
                    "brand_Food_1",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("product_Food_1", models.CharField(max_length=255)),
                (
                    "brand_Food_2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("product_Food_2", models.CharField(max_length=255)),
                ("apprise_methods", models.ManyToManyField(to="form.apprisemethod")),
                (
                    "pastuse_brands",
                    models.ManyToManyField(related_name="pastuse", to="form.brand"),
                ),
                (
                    "produse_brands",
                    models.ManyToManyField(related_name="produse", to="form.brand"),
                ),
                (
                    "seen_brands",
                    models.ManyToManyField(related_name="seen", to="form.brand"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RememberedBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scenes_description", models.TextField()),
                ("seen_objects", models.TextField()),
                ("audio", models.IntegerField()),
                ("caption", models.TextField()),
                ("used_brand", models.BooleanField()),
                ("used_product", models.BooleanField()),
                ("usage_brand", models.IntegerField()),
                ("usage_product", models.IntegerField()),
                ("brand_ads_seen", models.BooleanField()),
                ("ad_seen", models.BooleanField()),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="form.brand"
                    ),
                ),
                ("emotions", models.ManyToManyField(to="form.emotions")),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="form.experience",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OverallQuestionSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="form.experience",
                    ),
                ),
                ("remembered_brands", models.ManyToManyField(to="form.brand")),
            ],
        ),
        migrations.AddField(
            model_name="experience",
            name="videos",
            field=models.ManyToManyField(to="form.video"),
        ),
    ]
