# Generated by Django 4.1.3 on 2022-12-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="url",
            new_name="path",
        ),
    ]
