# Generated by Django 4.1.3 on 2022-12-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="yt_sub1",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
