# Generated by Django 4.1.3 on 2022-12-09 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="overallquestionsurvey",
            name="Automobiles_and_Travel_Industry_seen",
        ),
        migrations.RemoveField(
            model_name="overallquestionsurvey",
            name="Clothing_and_Apparel_seen",
        ),
        migrations.RemoveField(
            model_name="overallquestionsurvey",
            name="Cosmetics_seen",
        ),
        migrations.RemoveField(
            model_name="overallquestionsurvey",
            name="Defence_seen",
        ),
        migrations.RemoveField(
            model_name="overallquestionsurvey",
            name="Education_seen",
        ),
        migrations.RemoveField(
            model_name="overallquestionsurvey",
            name="Electronics_seen",
        ),
        migrations.RemoveField(
            model_name="overallquestionsurvey",
            name="Energy_seen",
        ),
        migrations.RemoveField(
            model_name="overallquestionsurvey",
            name="Finance_and_Banking_seen",
        ),
        migrations.RemoveField(
            model_name="overallquestionsurvey",
            name="Food_and_Beverages_seen",
        ),
        migrations.RemoveField(
            model_name="overallquestionsurvey",
            name="Healthcare_and_Pharmaceutical_seen",
        ),
        migrations.RemoveField(
            model_name="overallquestionsurvey",
            name="Software_Industry_seen",
        ),
        migrations.RemoveField(
            model_name="overallquestionsurvey",
            name="Telecom_seen",
        ),
        migrations.RemoveField(
            model_name="rememberedbrand",
            name="brand_ads_seen",
        ),
        migrations.RemoveField(
            model_name="rememberedbrand",
            name="caption",
        ),
        migrations.RemoveField(
            model_name="rememberedbrand",
            name="emotions",
        ),
        migrations.RemoveField(
            model_name="rememberedbrand",
            name="seen_objects",
        ),
        migrations.RemoveField(
            model_name="rememberedbrand",
            name="usage_brand",
        ),
        migrations.RemoveField(
            model_name="rememberedbrand",
            name="used_product",
        ),
        migrations.DeleteModel(
            name="Emotions",
        ),
    ]
