# Generated by Django 4.1.3 on 2022-12-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0002_rename_url_video_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="survey",
            name="pastuse_brands",
        ),
        migrations.DeleteModel(
            name="UserPastuse",
        ),
    ]
