# Generated by Django 4.1.3 on 2022-12-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0002_survey_yt_sub1"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="survey",
            name="yt_sub1",
        ),
        migrations.AddField(
            model_name="survey",
            name="nouse_brands",
            field=models.ManyToManyField(
                related_name="pastuse_brands", to="form.brand"
            ),
        ),
    ]
