# Generated by Django 4.0.6 on 2022-12-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_rememberedbrand_attention_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiddensurvey',
            name='prod_clear',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
