# Generated by Django 4.1.3 on 2022-12-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0004_remove_survey_nouse_brands_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="pastuse_brands",
            field=models.ManyToManyField(
                related_name="produse_brands", to="form.brand"
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="produse_brands",
            field=models.ManyToManyField(related_name="seen_brands", to="form.brand"),
        ),
    ]
