# Generated by Django 4.1.3 on 2022-12-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0004_overallquestionsurvey_defence_seen_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="overallquestionsurvey",
            old_name="Automobiles_seen",
            new_name="Automobiles and Travel Industry_seen",
        ),
        migrations.RenameField(
            model_name="overallquestionsurvey",
            old_name="Food_seen",
            new_name="Education_seen",
        ),
        migrations.RenameField(
            model_name="overallquestionsurvey",
            old_name="Healthcare_seen",
            new_name="Energy_seen",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="brand_Defence",
        ),
        migrations.AddField(
            model_name="overallquestionsurvey",
            name="Finance and Banking_seen",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="overallquestionsurvey",
            name="Food and Beverages_seen",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="overallquestionsurvey",
            name="Healthcare and Pharmaceutical_seen",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="overallquestionsurvey",
            name="Software Industry_seen",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
