# Generated by Django 4.1.3 on 2022-12-08 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "form",
            "0005_rename_automobiles_seen_overallquestionsurvey_automobiles and travel industry_seen_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="overallquestionsurvey",
            old_name="Automobiles and Travel Industry_seen",
            new_name="seen_Automobiles_and_Travel_Industry",
        ),
        migrations.RenameField(
            model_name="overallquestionsurvey",
            old_name="Clothing and Apparel_seen",
            new_name="seen_Clothing_and_Apparel",
        ),
        migrations.RenameField(
            model_name="overallquestionsurvey",
            old_name="Cosmetics_seen",
            new_name="seen_Cosmetics",
        ),
        migrations.RenameField(
            model_name="overallquestionsurvey",
            old_name="Defence_seen",
            new_name="seen_Defence",
        ),
        migrations.RenameField(
            model_name="overallquestionsurvey",
            old_name="Education_seen",
            new_name="seen_Education",
        ),
        migrations.RenameField(
            model_name="overallquestionsurvey",
            old_name="Electronics_seen",
            new_name="seen_Electronics",
        ),
        migrations.RenameField(
            model_name="overallquestionsurvey",
            old_name="Energy_seen",
            new_name="seen_Energy",
        ),
        migrations.RenameField(
            model_name="overallquestionsurvey",
            old_name="Finance and Banking_seen",
            new_name="seen_Finance_and_Banking",
        ),
        migrations.RenameField(
            model_name="overallquestionsurvey",
            old_name="Food and Beverages_seen",
            new_name="seen_Food_and_Beverages",
        ),
        migrations.RenameField(
            model_name="overallquestionsurvey",
            old_name="Healthcare and Pharmaceutical_seen",
            new_name="seen_Healthcare_and_Pharmaceutical",
        ),
        migrations.RenameField(
            model_name="overallquestionsurvey",
            old_name="Software Industry_seen",
            new_name="seen_Software_Industry",
        ),
        migrations.RenameField(
            model_name="overallquestionsurvey",
            old_name="Telecom_seen",
            new_name="seen_Telecom",
        ),
    ]
