# Generated by Django 4.1.3 on 2022-12-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0006_survey_newuse_brands_alter_survey_pastuse_brands_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppriseMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="survey",
            name="newuse_brands",
        ),
        migrations.AddField(
            model_name="survey",
            name="youtube_percentage",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survey",
            name="apprise_methods",
            field=models.ManyToManyField(to="form.apprisemethod"),
        ),
    ]
