# Generated by Django 4.1.3 on 2022-12-09 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "form",
            "0007_rename_seen_automobiles_and_travel_industry_overallquestionsurvey_automobiles_and_travel_industry_se",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="survey",
            name="brand_Automobiles",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="brand_Clothing and Apparel",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="brand_Cosmetics",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="brand_Electronics",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="brand_Food",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="brand_Healthcare",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="brand_Telecom",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="gpa",
        ),
    ]
