# Generated by Django 4.1.3 on 2022-12-09 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("form", "0008_remove_survey_brand_automobiles_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HiddenSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad_seen", models.BooleanField()),
                ("brand_ads_seen", models.BooleanField()),
                ("brand_heard", models.BooleanField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("video", models.ManyToManyField(to="form.video")),
            ],
        ),
    ]
