# Generated by Django 4.1.3 on 2022-12-07 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0009_video_experience"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="url",
        ),
        migrations.CreateModel(
            name="RememberedBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("used_product", models.BooleanField()),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="form.brand"
                    ),
                ),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="form.experience",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OverallQuestionSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="form.experience",
                    ),
                ),
                ("remembered_brands", models.ManyToManyField(to="form.brand")),
            ],
        ),
    ]
