# Generated by Django 4.1.3 on 2022-12-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0010_remove_video_url_rememberedbrand_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="url",
            field=models.CharField(default="lol", max_length=255),
            preserve_default=False,
        ),
    ]
