# Generated by Django 4.1.3 on 2022-12-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0011_video_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emotions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emotion", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="rememberedbrand",
            name="ad_seen",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rememberedbrand",
            name="audio",
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rememberedbrand",
            name="brand_ads_seen",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rememberedbrand",
            name="caption",
            field=models.TextField(default="x"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rememberedbrand",
            name="scenes_description",
            field=models.TextField(default="x"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rememberedbrand",
            name="seen_objects",
            field=models.TextField(default="x"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rememberedbrand",
            name="usage_brand",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rememberedbrand",
            name="usage_product",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rememberedbrand",
            name="used_brand",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rememberedbrand",
            name="emotions",
            field=models.ManyToManyField(to="form.emotions"),
        ),
    ]
